### ISSUE TITLE
[FEATURE REQUEST] Probing for the Tablet extension

### ISSUE THREAD

**Issue by lytke** [michmela44/ESP3D-WEBUI#2]
**Is your feature request related to a problem? Please describe.**
Tablet extension works well but lacks a feature to probe height of Z

**Describe the solution you'd like**
Menu at top right corner has a few options for homing and reset etc, if probing could be added there it would be perfect. Perhaps open a new dialog window similar to when clicking on one of the axis to change or goto new position.

**Comment by michmela44** [comment]
The tablet extension is written and maintained by Mitch Bradley.

The repo is here https://github.com/MitchBradley/WebUI-tablet-extension

That would be the best place for feedback about that specific extension
